/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanySettings {
  'adminPrincipal' : string,
  'createdAt' : Time,
  'logoUrl' : string,
  'companyName' : string,
  'fleetSize' : string,
  'industry' : string,
  'contactPhone' : string,
}
export interface CompanyUserInfo {
  'principal' : Principal,
  'role' : FleetRole,
  'profile' : [] | [UserProfile],
}
export interface DashboardStats {
  'activeVehicles' : bigint,
  'totalVehicles' : bigint,
  'upcomingMaintenanceCount' : bigint,
  'overdueCount' : bigint,
  'lowStockPartsCount' : bigint,
}
export interface DiscountCode {
  'id' : bigint,
  'value' : bigint,
  'code' : string,
  'createdAt' : Time,
  'discountType' : string,
  'usedCount' : bigint,
  'description' : string,
}
export type FleetRole = { 'FleetManager' : null } |
  { 'Mechanic' : null } |
  { 'Admin' : null };
export interface InviteToken {
  'token' : string,
  'usedBy' : [] | [Principal],
  'createdAt' : Time,
  'role' : FleetRole,
  'email' : string,
  'companyId' : string,
}
export interface MaintenanceRecordFull {
  'id' : bigint,
  'mileage' : bigint,
  'technicianName' : string,
  'partQuantities' : Array<PartQuantity>,
  'nextServiceDate' : [] | [Time],
  'cost' : number,
  'date' : Time,
  'createdAt' : Time,
  'partsUsed' : Array<bigint>,
  'laborHours' : [] | [number],
  'description' : string,
  'workOrderId' : [] | [bigint],
  'maintenanceType' : MaintenanceType,
  'laborCost' : [] | [number],
  'vehicleId' : bigint,
}
export type MaintenanceType = { 'OilChange' : null } |
  { 'Inspection' : null } |
  { 'TireRotation' : null } |
  { 'Transmission' : null } |
  { 'Bodywork' : null } |
  { 'BrakeService' : null } |
  { 'Electrical' : null } |
  { 'Other' : null } |
  { 'EngineCheck' : null };
export interface PartFull {
  'id' : bigint,
  'partNumber' : string,
  'quantityInStock' : bigint,
  'name' : string,
  'createdAt' : Time,
  'minStockLevel' : bigint,
  'category' : [] | [string],
  'price' : [] | [number],
  'location' : string,
}
export interface PartQuantity { 'quantity' : bigint, 'partId' : bigint }
export interface ServiceSchedule {
  'id' : bigint,
  'status' : string,
  'serviceType' : string,
  'lastCompletedDate' : [] | [Time],
  'nextDueDate' : Time,
  'createdAt' : Time,
  'intervalDays' : bigint,
  'notes' : string,
  'vehicleId' : bigint,
}
export interface SubscriptionRecord {
  'status' : string,
  'plan' : string,
  'updatedAt' : Time,
  'companyName' : string,
  'trialEndsAt' : [] | [Time],
  'startDate' : [] | [Time],
}
export interface TaxSettings {
  'taxEnabled' : boolean,
  'taxLabel' : string,
  'taxRate' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'status' : VehicleStatus,
  'model' : string,
  'vehicleType' : VehicleType,
  'licensePlate' : string,
  'make' : string,
  'name' : string,
  'createdAt' : Time,
  'year' : bigint,
  'notes' : string,
}
export type VehicleStatus = { 'Inactive' : null } |
  { 'Active' : null };
export type VehicleType = { 'Bus' : null } |
  { 'Van' : null } |
  { 'Trailer' : null } |
  { 'Truck' : null } |
  { 'Other' : null };
export interface Vendor {
  'id' : bigint,
  'contactName' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'address' : string,
  'notes' : string,
  'category' : string,
  'phone' : string,
}
export interface Warranty {
  'id' : bigint,
  'provider' : string,
  'expiryDate' : Time,
  'cost' : number,
  'coverageDetails' : string,
  'createdAt' : Time,
  'description' : string,
  'notes' : string,
  'vehicleId' : bigint,
  'startDate' : Time,
}
export interface WorkOrder {
  'id' : bigint,
  'completedDate' : [] | [Time],
  'status' : WorkOrderStatus,
  'title' : string,
  'scheduledDate' : [] | [Time],
  'createdAt' : Time,
  'description' : string,
  'notes' : string,
  'priority' : WorkOrderPriority,
  'assignedMechanic' : string,
  'vehicleId' : bigint,
}
export type WorkOrderPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type WorkOrderStatus = { 'Open' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyDiscountCode' : ActorMethod<[string], undefined>,
  'approveCompany' : ActorMethod<[string], undefined>,
  'approveCompanyWithKey' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkCreateVehicles' : ActorMethod<[Array<Vehicle>], Array<bigint>>,
  'cancelSubscription' : ActorMethod<[string], undefined>,
  'completeWorkOrder' : ActorMethod<[bigint], bigint>,
  'createDiscountCode' : ActorMethod<[DiscountCode], bigint>,
  'createDiscountCodeWithKey' : ActorMethod<[string, DiscountCode], bigint>,
  'createInviteToken' : ActorMethod<[string, FleetRole], string>,
  'createMaintenanceRecord' : ActorMethod<[MaintenanceRecordFull], bigint>,
  'createPart' : ActorMethod<[PartFull], bigint>,
  'createServiceSchedule' : ActorMethod<[ServiceSchedule], bigint>,
  'createVehicle' : ActorMethod<[Vehicle], bigint>,
  'createVendor' : ActorMethod<[Vendor], bigint>,
  'createWarranty' : ActorMethod<[Warranty], bigint>,
  'createWorkOrder' : ActorMethod<[WorkOrder], bigint>,
  'deleteDiscountCode' : ActorMethod<[string], undefined>,
  'deleteDiscountCodeWithKey' : ActorMethod<[string, bigint], undefined>,
  'deletePart' : ActorMethod<[bigint], undefined>,
  'deleteServiceSchedule' : ActorMethod<[bigint], undefined>,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'deleteWarranty' : ActorMethod<[bigint], undefined>,
  'deleteWorkOrder' : ActorMethod<[bigint], undefined>,
  'getAllCompanyApprovalsWithKey' : ActorMethod<
    [string],
    Array<[string, string]>
  >,
  'getAllCompanyRegistrations' : ActorMethod<[], Array<CompanySettings>>,
  'getAllCompanyRegistrationsWithKey' : ActorMethod<
    [string],
    Array<CompanySettings>
  >,
  'getAllDiscountCodesWithKey' : ActorMethod<[string], Array<DiscountCode>>,
  'getAllMaintenanceRecords' : ActorMethod<[], Array<MaintenanceRecordFull>>,
  'getAllParts' : ActorMethod<[], Array<PartFull>>,
  'getAllServiceSchedules' : ActorMethod<[], Array<ServiceSchedule>>,
  'getAllSubscriptions' : ActorMethod<[], Array<SubscriptionRecord>>,
  'getAllSubscriptionsWithKey' : ActorMethod<
    [string],
    Array<SubscriptionRecord>
  >,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getAllWarranties' : ActorMethod<[], Array<Warranty>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getCallerCompanyId' : ActorMethod<[], [] | [string]>,
  'getCallerFleetRole' : ActorMethod<[], [] | [FleetRole]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyApprovalStatus' : ActorMethod<[string], string>,
  'getCompanyApprovalStatusWithKey' : ActorMethod<[string, string], string>,
  'getCompanySettings' : ActorMethod<[], [] | [CompanySettings]>,
  'getCompanyUsers' : ActorMethod<[], Array<CompanyUserInfo>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDefaultCurrency' : ActorMethod<[], string>,
  'getDiscountCodes' : ActorMethod<[], Array<DiscountCode>>,
  'getInviteTokens' : ActorMethod<[], Array<InviteToken>>,
  'getLowStockParts' : ActorMethod<[], Array<PartFull>>,
  'getMaintenanceRecord' : ActorMethod<[bigint], MaintenanceRecordFull>,
  'getMaintenanceRecordsByVehicle' : ActorMethod<
    [bigint],
    Array<MaintenanceRecordFull>
  >,
  'getOverdueMaintenance' : ActorMethod<[], Array<MaintenanceRecordFull>>,
  'getPart' : ActorMethod<[bigint], PartFull>,
  'getSubscriptionStatus' : ActorMethod<[string], [] | [SubscriptionRecord]>,
  'getTaxSettings' : ActorMethod<[], [] | [TaxSettings]>,
  'getUpcomingMaintenance' : ActorMethod<[], Array<MaintenanceRecordFull>>,
  'getUserFleetRole' : ActorMethod<[Principal], [] | [FleetRole]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], Vehicle>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'getWarrantiesByVehicle' : ActorMethod<[bigint], Array<Warranty>>,
  'getWarranty' : ActorMethod<[bigint], Warranty>,
  'getWorkOrder' : ActorMethod<[bigint], WorkOrder>,
  'getWorkOrdersByVehicle' : ActorMethod<[bigint], Array<WorkOrder>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markScheduleComplete' : ActorMethod<[bigint], undefined>,
  'redeemInviteToken' : ActorMethod<[string], FleetRole>,
  'rejectCompany' : ActorMethod<[string], undefined>,
  'rejectCompanyWithKey' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'saveDefaultCurrency' : ActorMethod<[string], undefined>,
  'saveTaxSettings' : ActorMethod<[TaxSettings], undefined>,
  'setUserFleetRole' : ActorMethod<[Principal, FleetRole], undefined>,
  'startTrial' : ActorMethod<[string], undefined>,
  'startTrialWithKey' : ActorMethod<[string, string, bigint], undefined>,
  'updateMaintenanceRecord' : ActorMethod<
    [bigint, MaintenanceRecordFull],
    undefined
  >,
  'updatePart' : ActorMethod<[bigint, PartFull], undefined>,
  'updateServiceSchedule' : ActorMethod<[bigint, ServiceSchedule], undefined>,
  'updateSubscriptionStatus' : ActorMethod<
    [string, string, [] | [Time]],
    undefined
  >,
  'updateSubscriptionStatusWithKey' : ActorMethod<
    [string, string, string, [] | [Time]],
    undefined
  >,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], undefined>,
  'updateVendor' : ActorMethod<[bigint, Vendor], undefined>,
  'updateWarranty' : ActorMethod<[bigint, Warranty], undefined>,
  'updateWorkOrder' : ActorMethod<[bigint, WorkOrder], undefined>,
  'validateDiscountCode' : ActorMethod<[string], [] | [DiscountCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];