/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MaintenanceType = IDL.Variant({
  'OilChange' : IDL.Null,
  'Inspection' : IDL.Null,
  'TireRotation' : IDL.Null,
  'Transmission' : IDL.Null,
  'Bodywork' : IDL.Null,
  'BrakeService' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
  'EngineCheck' : IDL.Null,
});
export const MaintenanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'mileage' : IDL.Nat,
  'technicianName' : IDL.Text,
  'nextServiceDate' : IDL.Opt(Time),
  'cost' : IDL.Float64,
  'date' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'maintenanceType' : MaintenanceType,
  'vehicleId' : IDL.Nat,
});
export const Status = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'Bus' : IDL.Null,
  'Van' : IDL.Null,
  'Trailer' : IDL.Null,
  'Truck' : IDL.Null,
  'Other' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'licensePlate' : IDL.Text,
  'make' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'year' : IDL.Nat,
  'notes' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'activeVehicles' : IDL.Nat,
  'totalVehicles' : IDL.Nat,
  'upcomingMaintenanceCount' : IDL.Nat,
  'overdueCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMaintenanceRecord' : IDL.Func([MaintenanceRecord], [IDL.Nat], []),
  'createVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'getAllMaintenanceRecords' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMaintenanceRecord' : IDL.Func([IDL.Nat], [MaintenanceRecord], ['query']),
  'getMaintenanceRecordsByVehicle' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getOverdueMaintenance' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getUpcomingMaintenance' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMaintenanceRecord' : IDL.Func([IDL.Nat, MaintenanceRecord], [], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MaintenanceType = IDL.Variant({
    'OilChange' : IDL.Null,
    'Inspection' : IDL.Null,
    'TireRotation' : IDL.Null,
    'Transmission' : IDL.Null,
    'Bodywork' : IDL.Null,
    'BrakeService' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
    'EngineCheck' : IDL.Null,
  });
  const MaintenanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'mileage' : IDL.Nat,
    'technicianName' : IDL.Text,
    'nextServiceDate' : IDL.Opt(Time),
    'cost' : IDL.Float64,
    'date' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'maintenanceType' : MaintenanceType,
    'vehicleId' : IDL.Nat,
  });
  const Status = IDL.Variant({ 'Inactive' : IDL.Null, 'Active' : IDL.Null });
  const VehicleType = IDL.Variant({
    'Bus' : IDL.Null,
    'Van' : IDL.Null,
    'Trailer' : IDL.Null,
    'Truck' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'licensePlate' : IDL.Text,
    'make' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'year' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'activeVehicles' : IDL.Nat,
    'totalVehicles' : IDL.Nat,
    'upcomingMaintenanceCount' : IDL.Nat,
    'overdueCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMaintenanceRecord' : IDL.Func([MaintenanceRecord], [IDL.Nat], []),
    'createVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'getAllMaintenanceRecords' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMaintenanceRecord' : IDL.Func(
        [IDL.Nat],
        [MaintenanceRecord],
        ['query'],
      ),
    'getMaintenanceRecordsByVehicle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getOverdueMaintenance' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getUpcomingMaintenance' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMaintenanceRecord' : IDL.Func([IDL.Nat, MaintenanceRecord], [], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };