/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'activeVehicles' : bigint,
  'totalVehicles' : bigint,
  'upcomingMaintenanceCount' : bigint,
  'overdueCount' : bigint,
}
export interface MaintenanceRecord {
  'id' : bigint,
  'mileage' : bigint,
  'technicianName' : string,
  'nextServiceDate' : [] | [Time],
  'cost' : number,
  'date' : Time,
  'createdAt' : Time,
  'description' : string,
  'maintenanceType' : MaintenanceType,
  'vehicleId' : bigint,
}
export type MaintenanceType = { 'OilChange' : null } |
  { 'Inspection' : null } |
  { 'TireRotation' : null } |
  { 'Transmission' : null } |
  { 'Bodywork' : null } |
  { 'BrakeService' : null } |
  { 'Electrical' : null } |
  { 'Other' : null } |
  { 'EngineCheck' : null };
export type Status = { 'Inactive' : null } |
  { 'Active' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'status' : Status,
  'model' : string,
  'vehicleType' : VehicleType,
  'licensePlate' : string,
  'make' : string,
  'name' : string,
  'createdAt' : Time,
  'year' : bigint,
  'notes' : string,
}
export type VehicleType = { 'Bus' : null } |
  { 'Van' : null } |
  { 'Trailer' : null } |
  { 'Truck' : null } |
  { 'Other' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMaintenanceRecord' : ActorMethod<[MaintenanceRecord], bigint>,
  'createVehicle' : ActorMethod<[Vehicle], bigint>,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'getAllMaintenanceRecords' : ActorMethod<[], Array<MaintenanceRecord>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMaintenanceRecord' : ActorMethod<[bigint], MaintenanceRecord>,
  'getMaintenanceRecordsByVehicle' : ActorMethod<
    [bigint],
    Array<MaintenanceRecord>
  >,
  'getOverdueMaintenance' : ActorMethod<[], Array<MaintenanceRecord>>,
  'getUpcomingMaintenance' : ActorMethod<[], Array<MaintenanceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], Vehicle>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMaintenanceRecord' : ActorMethod<
    [bigint, MaintenanceRecord],
    undefined
  >,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];