/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FleetRole = IDL.Variant({
  'FleetManager' : IDL.Null,
  'Mechanic' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VehicleStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'Bus' : IDL.Null,
  'Van' : IDL.Null,
  'Trailer' : IDL.Null,
  'Truck' : IDL.Null,
  'Other' : IDL.Null,
});
export const Time = IDL.Int;
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'status' : VehicleStatus,
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'licensePlate' : IDL.Text,
  'make' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'year' : IDL.Nat,
  'notes' : IDL.Text,
});
export const DiscountCode = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'createdAt' : Time,
  'discountType' : IDL.Text,
  'usedCount' : IDL.Nat,
  'description' : IDL.Text,
});
export const ChecklistItemStatus = IDL.Variant({
  'NA' : IDL.Null,
  'Fail' : IDL.Null,
  'Pass' : IDL.Null,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : ChecklistItemStatus,
  'itemLabel' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
});
export const InspectionChecklist = IDL.Record({
  'id' : IDL.Nat,
  'mileage' : IDL.Nat,
  'inspectorName' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'items' : IDL.Vec(ChecklistItem),
  'overallStatus' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const PartQuantity = IDL.Record({
  'quantity' : IDL.Nat,
  'partId' : IDL.Nat,
});
export const MaintenanceType = IDL.Variant({
  'OilChange' : IDL.Null,
  'Inspection' : IDL.Null,
  'TireRotation' : IDL.Null,
  'Transmission' : IDL.Null,
  'Bodywork' : IDL.Null,
  'BrakeService' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
  'EngineCheck' : IDL.Null,
});
export const MaintenanceRecordFull = IDL.Record({
  'id' : IDL.Nat,
  'mileage' : IDL.Nat,
  'technicianName' : IDL.Text,
  'partQuantities' : IDL.Vec(PartQuantity),
  'nextServiceDate' : IDL.Opt(Time),
  'cost' : IDL.Float64,
  'date' : Time,
  'createdAt' : Time,
  'partsUsed' : IDL.Vec(IDL.Nat),
  'laborHours' : IDL.Opt(IDL.Float64),
  'description' : IDL.Text,
  'workOrderId' : IDL.Opt(IDL.Nat),
  'maintenanceType' : MaintenanceType,
  'laborCost' : IDL.Opt(IDL.Float64),
  'vehicleId' : IDL.Nat,
});
export const NotificationSeverity = IDL.Variant({
  'Info' : IDL.Null,
  'Critical' : IDL.Null,
  'Warning' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'relatedEntityType' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'relatedEntityId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
  'severity' : NotificationSeverity,
});
export const PartFull = IDL.Record({
  'id' : IDL.Nat,
  'partNumber' : IDL.Text,
  'quantityInStock' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'minStockLevel' : IDL.Nat,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Float64),
  'location' : IDL.Text,
});
export const ServiceSchedule = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'lastCompletedDate' : IDL.Opt(Time),
  'nextDueDate' : Time,
  'createdAt' : Time,
  'intervalDays' : IDL.Nat,
  'notes' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const Warranty = IDL.Record({
  'id' : IDL.Nat,
  'provider' : IDL.Text,
  'expiryDate' : Time,
  'cost' : IDL.Float64,
  'coverageDetails' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'notes' : IDL.Text,
  'vehicleId' : IDL.Nat,
  'startDate' : Time,
});
export const WorkOrderStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const WorkOrderPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const WorkOrder = IDL.Record({
  'id' : IDL.Nat,
  'completedDate' : IDL.Opt(Time),
  'status' : WorkOrderStatus,
  'title' : IDL.Text,
  'scheduledDate' : IDL.Opt(Time),
  'createdAt' : Time,
  'description' : IDL.Text,
  'notes' : IDL.Text,
  'priority' : WorkOrderPriority,
  'assignedMechanic' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const CompanySettings = IDL.Record({
  'adminPrincipal' : IDL.Text,
  'createdAt' : Time,
  'logoUrl' : IDL.Text,
  'contactEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'fleetSize' : IDL.Text,
  'industry' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'growth' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
});
export const SubscriptionRecord = IDL.Record({
  'status' : IDL.Text,
  'plan' : IDL.Text,
  'tier' : SubscriptionTier,
  'updatedAt' : Time,
  'companyName' : IDL.Text,
  'vehicleLimit' : IDL.Nat,
  'trialEndsAt' : IDL.Opt(Time),
  'startDate' : IDL.Opt(Time),
});
export const SubscriptionWithVehicleCount = IDL.Record({
  'vehicleCount' : IDL.Nat,
  'record' : SubscriptionRecord,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CompanyUserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : FleetRole,
  'profile' : IDL.Opt(UserProfile),
});
export const DashboardStats = IDL.Record({
  'activeVehicles' : IDL.Nat,
  'totalVehicles' : IDL.Nat,
  'upcomingMaintenanceCount' : IDL.Nat,
  'overdueCount' : IDL.Nat,
  'lowStockPartsCount' : IDL.Nat,
});
export const InviteToken = IDL.Record({
  'token' : IDL.Text,
  'usedBy' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'role' : FleetRole,
  'email' : IDL.Text,
  'companyId' : IDL.Text,
});
export const TaxSettings = IDL.Record({
  'taxEnabled' : IDL.Bool,
  'taxLabel' : IDL.Text,
  'taxRate' : IDL.Float64,
});
export const VehicleImportRow = IDL.Record({
  'model' : IDL.Text,
  'vehicleType' : IDL.Text,
  'licensePlate' : IDL.Text,
  'make' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'rowIndex' : IDL.Nat,
  'notes' : IDL.Text,
});
export const VehicleImportValidationResult = IDL.Record({
  'parsedVehicle' : IDL.Opt(Vehicle),
  'errors' : IDL.Vec(IDL.Text),
  'rowIndex' : IDL.Nat,
  'warnings' : IDL.Vec(IDL.Text),
  'isValid' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addUserToCompanyWithKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, FleetRole],
      [],
      [],
    ),
  'applyDiscountCode' : IDL.Func([IDL.Text], [], []),
  'approveCompany' : IDL.Func([IDL.Text], [], []),
  'approveCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkCreateVehicles' : IDL.Func(
      [IDL.Vec(Vehicle)],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Nat), 'err' : IDL.Text })],
      [],
    ),
  'cancelSubscription' : IDL.Func([IDL.Text], [], []),
  'completeWorkOrder' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createDiscountCode' : IDL.Func([DiscountCode], [IDL.Nat], []),
  'createDiscountCodeWithKey' : IDL.Func(
      [IDL.Text, DiscountCode],
      [IDL.Nat],
      [],
    ),
  'createInspectionChecklist' : IDL.Func([InspectionChecklist], [IDL.Nat], []),
  'createInviteToken' : IDL.Func([IDL.Text, FleetRole], [IDL.Text], []),
  'createMaintenanceRecord' : IDL.Func([MaintenanceRecordFull], [IDL.Nat], []),
  'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
  'createPart' : IDL.Func([PartFull], [IDL.Nat], []),
  'createServiceSchedule' : IDL.Func([ServiceSchedule], [IDL.Nat], []),
  'createVehicle' : IDL.Func(
      [Vehicle],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
  'createWarranty' : IDL.Func([Warranty], [IDL.Nat], []),
  'createWorkOrder' : IDL.Func([WorkOrder], [IDL.Nat], []),
  'deleteCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteDiscountCode' : IDL.Func([IDL.Text], [], []),
  'deleteDiscountCodeWithKey' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteInspectionChecklist' : IDL.Func([IDL.Nat], [], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'deletePart' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceSchedule' : IDL.Func([IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'deleteWarranty' : IDL.Func([IDL.Nat], [], []),
  'deleteWorkOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllCompanyApprovalsWithKey' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllCompanyRegistrations' : IDL.Func(
      [],
      [IDL.Vec(CompanySettings)],
      ['query'],
    ),
  'getAllCompanyRegistrationsWithKey' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CompanySettings)],
      ['query'],
    ),
  'getAllDiscountCodesWithKey' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiscountCode)],
      ['query'],
    ),
  'getAllInspectionChecklists' : IDL.Func(
      [],
      [IDL.Vec(InspectionChecklist)],
      ['query'],
    ),
  'getAllMaintenanceRecords' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecordFull)],
      ['query'],
    ),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllParts' : IDL.Func([], [IDL.Vec(PartFull)], ['query']),
  'getAllServiceSchedules' : IDL.Func(
      [],
      [IDL.Vec(ServiceSchedule)],
      ['query'],
    ),
  'getAllSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionRecord)],
      ['query'],
    ),
  'getAllSubscriptionsWithKey' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SubscriptionWithVehicleCount)],
      ['query'],
    ),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getAllWarranties' : IDL.Func([], [IDL.Vec(Warranty)], ['query']),
  'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getCallerCompanyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerFleetRole' : IDL.Func([], [IDL.Opt(FleetRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyApprovalStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCompanyApprovalStatusWithKey' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      ['query'],
    ),
  'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
  'getCompanyUsers' : IDL.Func([], [IDL.Vec(CompanyUserInfo)], ['query']),
  'getCompanyUsersWithKey' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CompanyUserInfo)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDefaultCurrency' : IDL.Func([], [IDL.Text], ['query']),
  'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
  'getInspectionChecklist' : IDL.Func(
      [IDL.Nat],
      [InspectionChecklist],
      ['query'],
    ),
  'getInspectionChecklistsByVehicle' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(InspectionChecklist)],
      ['query'],
    ),
  'getInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
  'getLowStockParts' : IDL.Func([], [IDL.Vec(PartFull)], ['query']),
  'getMaintenanceRecord' : IDL.Func(
      [IDL.Nat],
      [MaintenanceRecordFull],
      ['query'],
    ),
  'getMaintenanceRecordsByVehicle' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceRecordFull)],
      ['query'],
    ),
  'getOverdueMaintenance' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecordFull)],
      ['query'],
    ),
  'getPart' : IDL.Func([IDL.Nat], [PartFull], ['query']),
  'getSubscriptionStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SubscriptionRecord)],
      ['query'],
    ),
  'getTaxSettings' : IDL.Func([], [IDL.Opt(TaxSettings)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpcomingMaintenance' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecordFull)],
      ['query'],
    ),
  'getUserFleetRole' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FleetRole)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'getWarrantiesByVehicle' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Warranty)],
      ['query'],
    ),
  'getWarranty' : IDL.Func([IDL.Nat], [Warranty], ['query']),
  'getWorkOrder' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
  'getWorkOrdersByVehicle' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'markScheduleComplete' : IDL.Func([IDL.Nat], [], []),
  'redeemInviteToken' : IDL.Func([IDL.Text], [FleetRole], []),
  'rejectCompany' : IDL.Func([IDL.Text], [], []),
  'rejectCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeUserFromCompanyWithKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanySettings' : IDL.Func(
      [CompanySettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveDefaultCurrency' : IDL.Func([IDL.Text], [], []),
  'saveTaxSettings' : IDL.Func([TaxSettings], [], []),
  'setCompanyTierWithKey' : IDL.Func(
      [IDL.Text, IDL.Text, SubscriptionTier],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setMySubscriptionTier' : IDL.Func(
      [SubscriptionTier],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUserFleetRole' : IDL.Func([IDL.Principal, FleetRole], [], []),
  'setUserFleetRoleWithKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, FleetRole],
      [],
      [],
    ),
  'startTrial' : IDL.Func([IDL.Text], [], []),
  'startTrialWithKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateInspectionChecklist' : IDL.Func(
      [IDL.Nat, InspectionChecklist],
      [],
      [],
    ),
  'updateMaintenanceRecord' : IDL.Func(
      [IDL.Nat, MaintenanceRecordFull],
      [],
      [],
    ),
  'updatePart' : IDL.Func([IDL.Nat, PartFull], [], []),
  'updateServiceSchedule' : IDL.Func([IDL.Nat, ServiceSchedule], [], []),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateSubscriptionStatusWithKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
  'updateWarranty' : IDL.Func([IDL.Nat, Warranty], [], []),
  'updateWorkOrder' : IDL.Func([IDL.Nat, WorkOrder], [], []),
  'validateBulkVehicleImport' : IDL.Func(
      [IDL.Vec(VehicleImportRow)],
      [IDL.Vec(VehicleImportValidationResult)],
      ['query'],
    ),
  'validateDiscountCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiscountCode)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FleetRole = IDL.Variant({
    'FleetManager' : IDL.Null,
    'Mechanic' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VehicleStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'Bus' : IDL.Null,
    'Van' : IDL.Null,
    'Trailer' : IDL.Null,
    'Truck' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Time = IDL.Int;
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'status' : VehicleStatus,
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'licensePlate' : IDL.Text,
    'make' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'year' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const DiscountCode = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'createdAt' : Time,
    'discountType' : IDL.Text,
    'usedCount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const ChecklistItemStatus = IDL.Variant({
    'NA' : IDL.Null,
    'Fail' : IDL.Null,
    'Pass' : IDL.Null,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : ChecklistItemStatus,
    'itemLabel' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
  });
  const InspectionChecklist = IDL.Record({
    'id' : IDL.Nat,
    'mileage' : IDL.Nat,
    'inspectorName' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'items' : IDL.Vec(ChecklistItem),
    'overallStatus' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const PartQuantity = IDL.Record({ 'quantity' : IDL.Nat, 'partId' : IDL.Nat });
  const MaintenanceType = IDL.Variant({
    'OilChange' : IDL.Null,
    'Inspection' : IDL.Null,
    'TireRotation' : IDL.Null,
    'Transmission' : IDL.Null,
    'Bodywork' : IDL.Null,
    'BrakeService' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
    'EngineCheck' : IDL.Null,
  });
  const MaintenanceRecordFull = IDL.Record({
    'id' : IDL.Nat,
    'mileage' : IDL.Nat,
    'technicianName' : IDL.Text,
    'partQuantities' : IDL.Vec(PartQuantity),
    'nextServiceDate' : IDL.Opt(Time),
    'cost' : IDL.Float64,
    'date' : Time,
    'createdAt' : Time,
    'partsUsed' : IDL.Vec(IDL.Nat),
    'laborHours' : IDL.Opt(IDL.Float64),
    'description' : IDL.Text,
    'workOrderId' : IDL.Opt(IDL.Nat),
    'maintenanceType' : MaintenanceType,
    'laborCost' : IDL.Opt(IDL.Float64),
    'vehicleId' : IDL.Nat,
  });
  const NotificationSeverity = IDL.Variant({
    'Info' : IDL.Null,
    'Critical' : IDL.Null,
    'Warning' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'relatedEntityType' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'relatedEntityId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
    'severity' : NotificationSeverity,
  });
  const PartFull = IDL.Record({
    'id' : IDL.Nat,
    'partNumber' : IDL.Text,
    'quantityInStock' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'minStockLevel' : IDL.Nat,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Float64),
    'location' : IDL.Text,
  });
  const ServiceSchedule = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'lastCompletedDate' : IDL.Opt(Time),
    'nextDueDate' : Time,
    'createdAt' : Time,
    'intervalDays' : IDL.Nat,
    'notes' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Warranty = IDL.Record({
    'id' : IDL.Nat,
    'provider' : IDL.Text,
    'expiryDate' : Time,
    'cost' : IDL.Float64,
    'coverageDetails' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'notes' : IDL.Text,
    'vehicleId' : IDL.Nat,
    'startDate' : Time,
  });
  const WorkOrderStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const WorkOrderPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const WorkOrder = IDL.Record({
    'id' : IDL.Nat,
    'completedDate' : IDL.Opt(Time),
    'status' : WorkOrderStatus,
    'title' : IDL.Text,
    'scheduledDate' : IDL.Opt(Time),
    'createdAt' : Time,
    'description' : IDL.Text,
    'notes' : IDL.Text,
    'priority' : WorkOrderPriority,
    'assignedMechanic' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const CompanySettings = IDL.Record({
    'adminPrincipal' : IDL.Text,
    'createdAt' : Time,
    'logoUrl' : IDL.Text,
    'contactEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'fleetSize' : IDL.Text,
    'industry' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'growth' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
  });
  const SubscriptionRecord = IDL.Record({
    'status' : IDL.Text,
    'plan' : IDL.Text,
    'tier' : SubscriptionTier,
    'updatedAt' : Time,
    'companyName' : IDL.Text,
    'vehicleLimit' : IDL.Nat,
    'trialEndsAt' : IDL.Opt(Time),
    'startDate' : IDL.Opt(Time),
  });
  const SubscriptionWithVehicleCount = IDL.Record({
    'vehicleCount' : IDL.Nat,
    'record' : SubscriptionRecord,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CompanyUserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : FleetRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const DashboardStats = IDL.Record({
    'activeVehicles' : IDL.Nat,
    'totalVehicles' : IDL.Nat,
    'upcomingMaintenanceCount' : IDL.Nat,
    'overdueCount' : IDL.Nat,
    'lowStockPartsCount' : IDL.Nat,
  });
  const InviteToken = IDL.Record({
    'token' : IDL.Text,
    'usedBy' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'role' : FleetRole,
    'email' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const TaxSettings = IDL.Record({
    'taxEnabled' : IDL.Bool,
    'taxLabel' : IDL.Text,
    'taxRate' : IDL.Float64,
  });
  const VehicleImportRow = IDL.Record({
    'model' : IDL.Text,
    'vehicleType' : IDL.Text,
    'licensePlate' : IDL.Text,
    'make' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'rowIndex' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const VehicleImportValidationResult = IDL.Record({
    'parsedVehicle' : IDL.Opt(Vehicle),
    'errors' : IDL.Vec(IDL.Text),
    'rowIndex' : IDL.Nat,
    'warnings' : IDL.Vec(IDL.Text),
    'isValid' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addUserToCompanyWithKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, FleetRole],
        [],
        [],
      ),
    'applyDiscountCode' : IDL.Func([IDL.Text], [], []),
    'approveCompany' : IDL.Func([IDL.Text], [], []),
    'approveCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkCreateVehicles' : IDL.Func(
        [IDL.Vec(Vehicle)],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Nat), 'err' : IDL.Text })],
        [],
      ),
    'cancelSubscription' : IDL.Func([IDL.Text], [], []),
    'completeWorkOrder' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createDiscountCode' : IDL.Func([DiscountCode], [IDL.Nat], []),
    'createDiscountCodeWithKey' : IDL.Func(
        [IDL.Text, DiscountCode],
        [IDL.Nat],
        [],
      ),
    'createInspectionChecklist' : IDL.Func(
        [InspectionChecklist],
        [IDL.Nat],
        [],
      ),
    'createInviteToken' : IDL.Func([IDL.Text, FleetRole], [IDL.Text], []),
    'createMaintenanceRecord' : IDL.Func(
        [MaintenanceRecordFull],
        [IDL.Nat],
        [],
      ),
    'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
    'createPart' : IDL.Func([PartFull], [IDL.Nat], []),
    'createServiceSchedule' : IDL.Func([ServiceSchedule], [IDL.Nat], []),
    'createVehicle' : IDL.Func(
        [Vehicle],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
    'createWarranty' : IDL.Func([Warranty], [IDL.Nat], []),
    'createWorkOrder' : IDL.Func([WorkOrder], [IDL.Nat], []),
    'deleteCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteDiscountCode' : IDL.Func([IDL.Text], [], []),
    'deleteDiscountCodeWithKey' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteInspectionChecklist' : IDL.Func([IDL.Nat], [], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'deletePart' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceSchedule' : IDL.Func([IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'deleteWarranty' : IDL.Func([IDL.Nat], [], []),
    'deleteWorkOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllCompanyApprovalsWithKey' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllCompanyRegistrations' : IDL.Func(
        [],
        [IDL.Vec(CompanySettings)],
        ['query'],
      ),
    'getAllCompanyRegistrationsWithKey' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CompanySettings)],
        ['query'],
      ),
    'getAllDiscountCodesWithKey' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiscountCode)],
        ['query'],
      ),
    'getAllInspectionChecklists' : IDL.Func(
        [],
        [IDL.Vec(InspectionChecklist)],
        ['query'],
      ),
    'getAllMaintenanceRecords' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecordFull)],
        ['query'],
      ),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllParts' : IDL.Func([], [IDL.Vec(PartFull)], ['query']),
    'getAllServiceSchedules' : IDL.Func(
        [],
        [IDL.Vec(ServiceSchedule)],
        ['query'],
      ),
    'getAllSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionRecord)],
        ['query'],
      ),
    'getAllSubscriptionsWithKey' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubscriptionWithVehicleCount)],
        ['query'],
      ),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getAllWarranties' : IDL.Func([], [IDL.Vec(Warranty)], ['query']),
    'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getCallerCompanyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerFleetRole' : IDL.Func([], [IDL.Opt(FleetRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyApprovalStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCompanyApprovalStatusWithKey' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
    'getCompanyUsers' : IDL.Func([], [IDL.Vec(CompanyUserInfo)], ['query']),
    'getCompanyUsersWithKey' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CompanyUserInfo)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDefaultCurrency' : IDL.Func([], [IDL.Text], ['query']),
    'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
    'getInspectionChecklist' : IDL.Func(
        [IDL.Nat],
        [InspectionChecklist],
        ['query'],
      ),
    'getInspectionChecklistsByVehicle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(InspectionChecklist)],
        ['query'],
      ),
    'getInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
    'getLowStockParts' : IDL.Func([], [IDL.Vec(PartFull)], ['query']),
    'getMaintenanceRecord' : IDL.Func(
        [IDL.Nat],
        [MaintenanceRecordFull],
        ['query'],
      ),
    'getMaintenanceRecordsByVehicle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceRecordFull)],
        ['query'],
      ),
    'getOverdueMaintenance' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecordFull)],
        ['query'],
      ),
    'getPart' : IDL.Func([IDL.Nat], [PartFull], ['query']),
    'getSubscriptionStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SubscriptionRecord)],
        ['query'],
      ),
    'getTaxSettings' : IDL.Func([], [IDL.Opt(TaxSettings)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpcomingMaintenance' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecordFull)],
        ['query'],
      ),
    'getUserFleetRole' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FleetRole)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'getWarrantiesByVehicle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Warranty)],
        ['query'],
      ),
    'getWarranty' : IDL.Func([IDL.Nat], [Warranty], ['query']),
    'getWorkOrder' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
    'getWorkOrdersByVehicle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'markScheduleComplete' : IDL.Func([IDL.Nat], [], []),
    'redeemInviteToken' : IDL.Func([IDL.Text], [FleetRole], []),
    'rejectCompany' : IDL.Func([IDL.Text], [], []),
    'rejectCompanyWithKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeUserFromCompanyWithKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanySettings' : IDL.Func(
        [CompanySettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveDefaultCurrency' : IDL.Func([IDL.Text], [], []),
    'saveTaxSettings' : IDL.Func([TaxSettings], [], []),
    'setCompanyTierWithKey' : IDL.Func(
        [IDL.Text, IDL.Text, SubscriptionTier],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setMySubscriptionTier' : IDL.Func(
        [SubscriptionTier],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUserFleetRole' : IDL.Func([IDL.Principal, FleetRole], [], []),
    'setUserFleetRoleWithKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, FleetRole],
        [],
        [],
      ),
    'startTrial' : IDL.Func([IDL.Text], [], []),
    'startTrialWithKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateInspectionChecklist' : IDL.Func(
        [IDL.Nat, InspectionChecklist],
        [],
        [],
      ),
    'updateMaintenanceRecord' : IDL.Func(
        [IDL.Nat, MaintenanceRecordFull],
        [],
        [],
      ),
    'updatePart' : IDL.Func([IDL.Nat, PartFull], [], []),
    'updateServiceSchedule' : IDL.Func([IDL.Nat, ServiceSchedule], [], []),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateSubscriptionStatusWithKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
    'updateWarranty' : IDL.Func([IDL.Nat, Warranty], [], []),
    'updateWorkOrder' : IDL.Func([IDL.Nat, WorkOrder], [], []),
    'validateBulkVehicleImport' : IDL.Func(
        [IDL.Vec(VehicleImportRow)],
        [IDL.Vec(VehicleImportValidationResult)],
        ['query'],
      ),
    'validateDiscountCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiscountCode)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };